name: LocatorBarRange
version: '1.0.0'
main: com.tcoded.locatorbarrange.LocatorBarRange
api-version: '1.21'
folia-supported: true

commands:
  locatorbarrange:
    description: Main command for LocatorBarRange plugin
    usage: /<command> reload
    permission: locatorbarrange.command.locatorbarrange
    aliases: [lbr]

permissions:
  locatorbarrange.command.locatorbarrange:
    description: Permission to use the /locatorbarrange command
    default: op
  locatorbarrange.group.admin:
    description: Default admin group for LocatorBarRange
    default: false
